// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMR6Ux91HIVJFrQmaY8hJJaR_CcsOtjoA',
    appId: '1:943899880144:web:e89d0a3014548e9fe08cd5',
    messagingSenderId: '943899880144',
    projectId: 'pcdmetro-2b041',
    authDomain: 'pcdmetro-2b041.firebaseapp.com',
    storageBucket: 'pcdmetro-2b041.appspot.com',
    measurementId: 'G-5VZGHZQG3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcJyi_nr1jIPQDyWEZyM8KRhvJCCCCtbc',
    appId: '1:943899880144:android:c923176528a0d3f3e08cd5',
    messagingSenderId: '943899880144',
    projectId: 'pcdmetro-2b041',
    storageBucket: 'pcdmetro-2b041.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHYYvd42QuQafhcPHQOzAJMVqQv96RuYI',
    appId: '1:943899880144:ios:97b7165608d4561ee08cd5',
    messagingSenderId: '943899880144',
    projectId: 'pcdmetro-2b041',
    storageBucket: 'pcdmetro-2b041.appspot.com',
    iosClientId: '943899880144-9b7dkiqrcskpth6ehadtu59hbbvf8tts.apps.googleusercontent.com',
    iosBundleId: 'com.example.pcdmetro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHYYvd42QuQafhcPHQOzAJMVqQv96RuYI',
    appId: '1:943899880144:ios:97b7165608d4561ee08cd5',
    messagingSenderId: '943899880144',
    projectId: 'pcdmetro-2b041',
    storageBucket: 'pcdmetro-2b041.appspot.com',
    iosClientId: '943899880144-9b7dkiqrcskpth6ehadtu59hbbvf8tts.apps.googleusercontent.com',
    iosBundleId: 'com.example.pcdmetro',
  );
}
